---
title: "Geospatial data cubes in Julia workshop"
---


This is the website of the "Geospatial data cubes in Julia workshop".

In this tutorial we will explore how to analyse raster data which is larger than RAM.

## Preparation

To participate in the hands-on parts of the tutorial please install Julia on your device 
and instantiate a first environment to make sure that most Julia packages are already downloaded on your computer.

### Installation of Julia
We recommend to use the [juliaup](https://github.com/JuliaLang/juliaup) installer for julia.


::: {.panel-tabset}

## Windows 

You can install juliaup via the windows store or by executing

```
winget install julia -s msstore
```

## Mac or Linux
To install juliaup in Linux or Mac execute the following in a shell

```sh
curl -fsSL https://install.julialang.org | sh
``` 

:::

### Instantiation of an initial environment 
For the workshop we are going to use the environment that is available of the examples folder.

::: {.panel-tabset}

## Manual download

You can download the Project.toml file from https://github.com/JuliaDataCubes/datacubes_in_julia_workshop/blob/main/examples/Project.toml manually and save it in a new folder.
Then change in a terminal to this folder.

## Use git

Use git to download the whole workshop material.

```
git clone https://github.com/JuliaDataCubes/datacubes_in_julia_workshop/
```
Change to the examples folder in the datacubes_in_julia_workshop folder.

:::



Now that we have the Project.toml file downloaded we can run the following line in the terminal from the folder in which the Project.toml is located.

```
julia -e 'using Pkg;Pkg.activate(".");Pkg.resolve();Pkg.precompile()'
``` 

# Timeline

This is a rough time line of the workshop hold on two half days. 

## Day 1 

| Time | Topic |
|:------|:---------|
| 9:00 |  Introduction to Datacube analysis | 
| 9:30 |  Introduction to Julia |
| 10:30 |  Break |
| 10:50 |  Exercise: Time series analysis + plotting | 


## Day 2

| Time | Topic |
|:------|:---------|
| 9:00 |  Introduction to YAXArrays.jl | 
| 9:45 |  Exercise: YAXArrays |
| 10:15 |  Break |
| 10:30 |  Excursion: Datacubes in python | 
| 10:45 |  Data preparation | 
| 11:15 |  PyramidScheme.jl | 

--- 
